finalYearProject/finalYearProject/Models/Restaurent.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace finalYearProject.Models
{
    public class Restaurent
    {
        [Required(ErrorMessage = "Please enter id in email format")]
        [EmailAddress]
        public string RestaurentID { get; set; }
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Must be at least 4 characters long.")]
        [Required(ErrorMessage = "Please enter Password")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter Name")]
        [StringLength(50)]
        public string NameOfRestaurants { get; set; }
        [Required(ErrorMessage = "Please enter Address")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Must be at least 10 characters long.")]
        public string Location { get; set; }

        [Required(ErrorMessage = "Please enter Phone No")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string PhoneNo { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public string OpenUntil { get; set; }
        
        [Required]
        public string DeliveryCharges { get; set; }

        public string PhotoPATH { get; set; }
      
        public IFormFile Photo { get; set; }
    }
}

finalYearProject/finalYearProject/Controllers/CafeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using finalYearProject.Models;
using finalYearProject.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace finalYearProject.Controllers
{
    [Authorize]
    public class CafeController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        public CafeController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
            
        }
        PUCITRepository pucitRepository = new PUCITRepository();
        public async Task<ActionResult> HomePage(string uname,string cafe,string clear)
        {
            if(clear=="clearcart")
            {
                pucitRepository.Cart.Clear();
                pucitRepository.ClearAllCart();
            }
                var user = await userManager.FindByIdAsync(uname);
            ViewBag.cafe = cafe;
            ViewBag.uname = uname;
            ViewBag.email = user.Email;
            return View();
        }
        public async Task<ViewResult> PucitCafe(string uname,string cafe,string clear)
        {
            ViewBag.clear = clear;
            var user = await userManager.FindByIdAsync(uname);
            ViewBag.uname = user.Id;
            ViewBag.cafe = cafe;
            ViewBag.email = user.Email;
            PUCITCategoryViewcs pUCITCategoryViewcs = new PUCITCategoryViewcs();
            pUCITCategoryViewcs.Category = pucitRepository.Category;
            return View("PucitCafe",pUCITCategoryViewcs);
        }
        public async Task<ViewResult> PharmacyCafe(string uname,string cafe,string clear)
        {
            ViewBag.clear = clear;
            var user = await userManager.FindByIdAsync(uname);
            ViewBag.uname = user.Id;
            ViewBag.cafe = cafe;
            ViewBag.email = user.Email;
            return View(pucitRepository.CategoryPharmacy);
        }
        public async Task<ViewResult> ProductsView(string CategoryName,string uname,string cafe,string email)
        {
            ViewBag.Categoryname = CategoryName;
            var user = await userManager.FindByIdAsync(uname);
            ViewBag.uname = user.Id;
            ViewBag.email = email;
            ViewBag.cafe = cafe;

            PUCITShowViewModel pUCITShowViewModel = new PUCITShowViewModel();
            pucitRepository.temp.Clear();
            foreach (PUCITProducts product in pucitRepository.products)
            {
                if (product.Category == CategoryName)
                {
                    pucitRepository.temp.Add(product);
                }
            }
            pUCITShowViewModel.productlist = pucitRepository.temp;
            pUCITShowViewModel.Category = pucitRepository.Category;
            return View(pUCITShowViewModel);
        }
        public async Task<ViewResult> ProductViewPharmacy(string CategoryName, string uname, string cafe,string email)
        {
            ViewBag.Categoryname = CategoryName;
            var user = await userManager.FindByIdAsync(uname);
            ViewBag.uname = user.Id;
            ViewBag.email = user.Email;
            ViewBag.cafe = cafe;

            PUCITShowViewModel pUCITShowViewModel = new PUCITShowViewModel();
            pucitRepository.temp.Clear();
            foreach (PUCITProducts product in pucitRepository.productsPharmacy)
            {
                if (product.Category == CategoryName)
                {
                    pucitRepository.temp.Add(product);
                }
            }
            pUCITShowViewModel.productlist = pucitRepository.temp;
            pUCITShowViewModel.Category = pucitRepository.CategoryPharmacy;
            return View(pUCITShowViewModel);
           
        }
        
        public async Task<ViewResult> SubmitOrder(string uname,string cafe,string email)
        {
            PUCITShowViewModel pUCITShowViewModel = new PUCITShowViewModel();
            var user = await userManager.FindByIdAsync(uname);
            ViewBag.uname = user.Id;
            ViewBag.cafe = cafe;
            ViewBag.email = email;
            pUCITShowViewModel.Category = pucitRepository.Category;
            return View(pUCITShowViewModel);
        }
        public async Task<ViewResult> SubmitOrderPharmacy(string uname, string cafe)
        {
            PUCITShowViewModel pUCITShowViewModel = new PUCITShowViewModel();
            var user = await userManager.FindByIdAsync(uname);
            ViewBag.uname = user.Id;
            ViewBag.cafe = cafe;
            pUCITShowViewModel.Category = pucitRepository.CategoryPharmacy;
            return View(pUCITShowViewModel);
        }
    }
}

finalYearProject/finalYearProject/Controllers/RestaurentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using finalYearProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace finalYearProject.Controllers
{
    public class RestaurentController : Controller
    {
        PUCITRepository pucitRepository = new PUCITRepository();
        public ViewResult RestaurentHomePage(string uname, string RestaurentID,string clear)
        {
            ViewBag.clear = clear;
            ViewBag.uname = uname;
            ViewBag.RestaurentID = RestaurentID;
            return View("RestaurentHomePage",pucitRepository.restaurents);
        }
        public ViewResult RestaurentMenue(string RestaurentID,string uname,string clear)
        {
            if(clear== "clearcart")
            {
                pucitRepository.Cart.Clear();
                pucitRepository.ClearAllCart();
            }
            ViewBag.uname = uname;
            ViewBag.RestaurentID = RestaurentID;
            Restaurent r = pucitRepository.restaurents.Find(r => r.RestaurentID == RestaurentID);
            foreach (RestaurentMenu res in pucitRepository.restaurentsMenu)
            {
                if (res.RestaurentID == RestaurentID)
                {
                    res.RestaurentName = r.NameOfRestaurants;
                    pucitRepository.tempres.Add(res);
                }
            }
            return View("RestaurentMenue", pucitRepository.tempres);
            //RestaurentMenu rm = RestaurentRepository.restaurentsMenu.Find(r => r.RestaurentID == RestaurentID);

        }
     
        public ViewResult MenueDetail(string RestaurentID, int MenuID,string uname)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            RestaurentMenu rm = pucitRepository.restaurentsMenu.Find(rm => rm.RestaurentID == RestaurentID && rm.MenuID == MenuID);
            return View("MenueDetail", rm);
        }
        [HttpPost]
        public ViewResult AddToCart(RestaurentMenu r,string uname)
        {    
            ViewBag.RestaurentID = r.RestaurentID;
            ViewBag.uname = uname;
            if (ModelState.IsValid)
            {
                if(r.SelectedQuantity<=0)
                {
                    ModelState.AddModelError(string.Empty, "Quantity cannot be less tha 0");
                    return View("MenueDetail", r);
                }    
                RestaurentMenu rm = pucitRepository.restaurentsMenu.Find(rm => rm.RestaurentID == r.RestaurentID && rm.MenuID == r.MenuID);
                CartAndOrder a = new CartAndOrder();
                // a.CartID = pucitRepository.Cart.Count + 1;
                a.RestaurentID = rm.RestaurentID;
                a.MenuID = rm.MenuID;
                a.UserID = uname;
                //a.Quantity = Convert.ToInt32(Request["TextQuintity"].ToString());
                a.Quantity = r.SelectedQuantity;
                a.OriginalPrice = rm.Price;
                a.Price = (Int32.Parse(rm.Price) * a.Quantity).ToString();
                a.NameOfItem = rm.NameOfItem;
                pucitRepository.AddCartD(a);
                // a.UserID = RestaurentRepository.GetUserId();
                //  RestaurentRepository.AddToCart(a);
                //RestaurentRepository.AddCartD(a);
                //return View("RestaurentCartView", RestaurentRepository.Cart);
                return RestaurentCartView(r.RestaurentID, uname);
            }
            return View("MenueDetail", r);
        }
        public ViewResult RestaurentCartView(string RestaurentID, string uname)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            foreach (CartAndOrder res in pucitRepository.Cart)
            {
                if (res.RestaurentID == RestaurentID && res.UserID ==uname)
                {
                    pucitRepository.CarttEMP.Add(res);
                }
            }
            viewmodel viewModel = new viewmodel();
            viewModel.Cart = pucitRepository.CarttEMP;
            Receipt re = new Receipt();
            viewModel.receipt = re;
            return View("RestaurentCartView", viewModel);
            
        }
        [HttpPost]
        public ViewResult PlaceOrder(viewmodel viewModel,string uname, string RestaurentID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            if (ModelState.IsValid)
            {
               
                Receipt receipt = new Receipt();
                receipt.ReceiptID = pucitRepository.restaurantPendingOrder.Count + 1;
                receipt.OrderTime = DateTime.Now;

                receipt.NoOfItems = pucitRepository.Cart.Count;
                receipt.RestaurentID = RestaurentID;
                receipt.OrderAccept = 0;
                receipt.OrderReceived = 0;
                receipt.TotalAmount = 0.ToString();
                receipt.UserTime = viewModel.receipt.UserTime;
                foreach (CartAndOrder cart in pucitRepository.Cart)
                {
                    receipt.UserID = cart.UserID;
                    cart.ReceiptID = receipt.ReceiptID;
                    receipt.TotalAmount = (Int32.Parse(receipt.TotalAmount) + Int32.Parse(cart.Price)).ToString();
                    pucitRepository.AddOrderD(cart);
                    pucitRepository.order.Add(cart);
                }
                pucitRepository.restaurantPendingOrder.Add(receipt);
                pucitRepository.AddReceiptD(receipt);
                pucitRepository.Cart.Clear();

                // pucitRepository.Cart.Clear();
                pucitRepository.ClearAllCart();
                //pending o
                return PendingOrder(uname, RestaurentID);
            }

            foreach (CartAndOrder res in pucitRepository.Cart)
            {
                if (res.RestaurentID == RestaurentID && res.UserID == uname)
                {
                    pucitRepository.CarttEMP.Add(res);
                }
            }
            viewmodel viewModel1 = new viewmodel();
            viewModel1.Cart = pucitRepository.CarttEMP;
            Receipt re = new Receipt();
            viewModel1.receipt = viewModel.receipt;
            return View("RestaurentCartView", viewModel1);
        }
        public ViewResult PendingOrder(string uname, string RestaurentID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            foreach (Receipt res in pucitRepository.restaurantPendingOrder)
            {
                if (res.RestaurentID == RestaurentID && res.UserID == uname && res.OrderAccept==0)
                {
                    pucitRepository.restaurantPendingOrderres.Add(res);
                }
            }
            return View("PendingOrder", pucitRepository.restaurantPendingOrderres);
        }
        public ViewResult HomePage(string uname, string RestaurentID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            return View("HomePage", pucitRepository.restaurents);
        }
        public ViewResult Detail(string uname, string RestaurentID,int receiptID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            ViewBag.ReceiptID = receiptID;
            return View("Detail", pucitRepository.order);
        }
        public ViewResult UserOrderList(string uname, string RestaurentID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            foreach (Receipt receipt in pucitRepository.restaurantPendingOrder)
            {
                if (receipt.RestaurentID == RestaurentID && receipt.UserID==uname && receipt.OrderAccept == 1)
                {
                    pucitRepository.restaurantOrderListres.Add(receipt);
                }
            }
            return View("UserOrderList", pucitRepository.restaurantOrderListres);
        }
        public ViewResult Clear(string uname, string RestaurentID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            pucitRepository.Cart.Clear();
           pucitRepository.ClearAllCart();
            viewmodel viewModel = new viewmodel();
            viewModel.Cart = pucitRepository.Cart;
            Receipt re = new Receipt();
            viewModel.receipt = re;
            return View("RestaurentCartView", viewModel);
            //return View("RestaurentCartView", RestaurentRepository.Cart);

        }
        public ViewResult Remove(int CartID, string uname, string RestaurentID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            CartAndOrder r = pucitRepository.Cart.Find(r => r.CartID == CartID);
            pucitRepository.Cart.Remove(r);
            pucitRepository.RemoveCart(r.CartID);
              return RestaurentCartView(RestaurentID,uname);
            // return View("RestaurentCartView", RestaurentRepository.Cart);


        }
        public ViewResult Increase(int CartID, string uname, string RestaurentID)
        {
            ViewBag.RestaurentID = RestaurentID;
            ViewBag.uname = uname;
            CartAndOrder r =pucitRepository.Cart.Find(r => r.CartID == CartID);


            foreach (CartAndOrder cart in pucitRepository.Cart)
            {

                if (cart.CartID == r.CartID)
                {

                    cart.Price = (Int32.Parse(r.OriginalPrice) * (r.Quantity + 1)).ToString();
                    cart.Quantity = r.Quantity + 1;
                    break;
                }

            }
           pucitRepository.EditCart(r);
            return RestaurentCartView(RestaurentID, uname);
        }
        public ViewResult Decrease(int CartID, string uname, string RestaurentID)
        {
            CartAndOrder r = pucitRepository.Cart.Find(r => r.CartID == CartID);

finalYearProject/finalYearProject/Views/Restaurent/Detail.cshtml
@model List<finalYearProject.Models.CartAndOrder>

@{ Layout = "~/Views/Shared/_Layout2.cshtml";
    var RestaurentID = ViewBag.RestaurentID;
    var uname = ViewBag.uname;
    
}
<section class="mainpart">
    <div class="container">
        <div class="col-lg-12 m-auto d-block card p-3 decorate">
            <br />
            <h2 class="text-center">A Order Detail</h2>
            <div>
                <table class="table table-dark table-hover table-striped ">
                    <thead>
                        <tr>
                            <th>
                                Name Of Item
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                Quantity
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (finalYearProject.Models.CartAndOrder r in Model)
                        {
                            @if (r.ReceiptID == @ViewBag.ReceiptID)
                            {
                                <tr>

                                    <td>
                                        @r.NameOfItem
                                    </td>
                                    <td>
                                        @r.Price

                                    </td>
                                    <td>
                                        @r.Quantity


                                    </td>



                                </tr>
                            }}

                    </tbody>





                </table>


            </div>
        </div>

    </div>
</section>

finalYearProject/finalYearProject/Views/Restaurent/HomePage.cshtml
@model List<finalYearProject.Models.Restaurent>
@{
      var RestaurentID = ViewBag.RestaurentID;
    var uname = ViewBag.uname;
}
<!DOCKTYPE html>
    <html>
    <head>

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <style>
            /* Make the image fully responsive */
            .carousel-inner img {
                width: 100%;
                height: 89%;
            }
              .h3{
            color:white;
        }
        .p {
            color:white;
            text-align:center;
            line-height:75px;
            font-size:large;
            background-color:black;
        }
            .footer {
                padding: 50px;
                text-align: center;
                color: white;
                background: black;
            }

            .menu .card-img-top {
                transition: all 0.3s ease-in-out;
            }

            .background {
                background-image: url('/images/owner2.jpg');
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;
                height: 100vh;
                width: 100%;
            }

            * {
                margin: 0;
                padding: 0;
                font-family: 'Josefin Sans',sans-serif;
            }

            .menu {
            }

                .menu .card {
                    border: 0;
                    margin-bottom: 40px;
                    position: relative;
                    background: transparent;
                }

                .menu .card-body {
                    z-index: 10;
                    background: #ff9b04a6;
                    backgorund-top: 4px solid #ff9b04a6;
                    padding: 3px;
                    box-shado: 0px 2px 15px rgba(241,159,5,0.5);
                    margin-top: -60px;
                    transition: 0.3s;
                }

                .menu .card-title {
                    font-weight: bold;
                    text-align: center;
                    margin-top: 20px;
                }

                    .menu .card-title a {
                        color: #000;
                        transition: 0.3s;
                    }

                .menu .card-text {
                    padding: 10px;
                }
        </style>
    </head>
    <body>
        <header>
            <!-- sTART OF hOME PAGE-->
            <!-- sTART OF hOME PAGE-->
            <nav class="navbar navbar-light bg-dark m-0">
                <div class="container-fluid" style="padding:10px;">
                    <a class="nav-link disabled" href="#" aria-disabled="true">Restaurant System</a>
                    <form class="d-flex">
                        <ul class=" nav justify-content-end">


                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-route-restaurentID="@RestaurentID" asp-route-uname="@uname" asp-action="HomePage">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-route-restaurentID="@RestaurentID" asp-route-uname="@uname" asp-action="RestaurentMenue">Menu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-route-RestaurentID="@RestaurentID" asp-route-uname="@uname" asp-action="RestaurentCartView"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-route-RestaurentID="@RestaurentID" asp-route-uname="@uname" asp-action="PendingOrder">Pending Order</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-route-RestaurentID="@RestaurentID" asp-route-uname="@uname" asp-action="UserOrderList">Order List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    </form>
                </div>
            </nav>
            <div class="background">
                <div>
                    <h1 class="text-white text-center" style="padding-top:100px;">Welcome to Restaurant Management System</h1>
                    <h3 class="text-white text-center">We are providing this for Years.</h3>
                </div>
            </div>
        </header>
        <section id="menu" class="menu ">
            <div class="container">
                <div class="section-title">
                    <h2 class="text-center font-weight-bold pt-5 text-capitalize">Available Restaurants</h2>
                    <hr class="2-25 mx-auto " />
                    <p>
                        In Restaurant Management System , There are list of avialable Restaurants you can order from any restaurant
                        .Than you will get Provide pickup time in which you want the food.
                    </p>
                </div>
                <!--START OF CARD DECTIOM-->
                <div class="row ">
                    @foreach (finalYearProject.Models.Restaurent p in Model)
                    {
                        <!--START OF CARD -->
                        <div class="col-md-6 d-flex align-items-stretch">
                            <div class="card ">
                                <!-- card -image-->
                                <img src="~/images/@p.PhotoPATH" style="height:400px;object-fit:cover;" class="card-img-top" alt="...">
                                <!--card -body-->
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a asp-route-clear="clearcart" asp-route-restaurentID="@p.RestaurentID" onclick="return confirm('Are you sure you wanant to exit this restaurant .If you have some products in the cart they will be removed')" asp-route-uname="@uname" asp-action="RestaurentMenue">@p.NameOfRestaurants</a>
                                    </h5>
                                    <p class="card-text">
                                        Location: @p.Location
                                        <br />
                                        Phone No: @p.PhoneNo
                                        <br />
                                        Open Untill: @p.OpenUntil
                                    </p>
                                </div>
                            </div>
                        </div>
                    }

                </div>
            </div>

        </section>


        <!--End of Home PAGE-->
        <!-- Start of Menu Section-->


        <div style="margin-bottom:20px;">
            <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d13597.459350046463!2d74.30212987654872!3d31.569041664019228!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sRestaurants%20%20near%20Punjab%20Universty%20old%20campus!5e0!3m2!1sen!2s!4v1617106747166!5m2!1sen!2s" width="1000" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>  
        <footer>
            <div style="background-color:#111111;padding:30px">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-one">
                            <h3 class="h3">Offers</h3>
                        </div>
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-two">
                            <h3 class="h3">Manage</h3>
                        </div>

                        <div class="col-md-4 col-sm-3 col-xl-4 segment-three">
                            <h3 class="h3">Restaurant Owner</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-one">
                            <a asp-route-clear="clearcart" asp-controller="Cafe" onclick="return confirm('Are you sure you want to exit if you have some products in the cart they will be removed')" asp-action="HomePage" asp-route-uname="@uname">Cafe</a>
                        </div>
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-two">
                            <a asp-route-uname="@uname" asp-action="changepasswd" asp-controller="Home">Change Password</a>
                        </div>
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-three">
                            <a asp-controller="RestaurentOwner" asp-action="OwnerLogin" asp-route-uname="@uname">Login</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-one">
                            <a asp-route-uname="@uname"></a>
                        </div>
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-two">
                            <a asp-route-uname="@uname" asp-action="userProfile" asp-controller="Home">Profile</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-3 col-xl-4 segment-one">
                            <a href="#"></a>
                        </div>

                        <div class="col-md-4 col-sm-3 col-xl-4 segment-two">
                            <a asp-route-uname="@uname" asp-action="RestaurentContactUs">Contact Us</a>
                        </div>
                    </div>
                </div>
            </div>
            <p class="p"> All Rights Reserved by Food Authority Pakistan2021 </p>

        </footer>
        <!-- Start of Menu Section-->

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>